In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\Alex Christopher\OneDrive\Desktop\Modular\ML_Live_Class\data\advertising.csv")
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [3]:
X = df.drop("Sales", axis=1)

In [4]:
y = df.Sales

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
poly_conv = PolynomialFeatures(degree=3, include_bias=False)
poly_conv

PolynomialFeatures(degree=3, include_bias=False)

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
model = LinearRegression()

In [9]:
poly_features = poly_conv.fit_transform(X)
poly_features

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [10]:
poly_features.shape

(200, 19)

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.33, random_state=101)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()

In [14]:
scaler.fit(X_train)

StandardScaler()

In [15]:
scaled_X_train = scaler.transform(X_train)

In [16]:
scaled_X_test = scaler.transform(X_test)

In [17]:
X_train[0]

array([1.87800000e+02, 2.11000000e+01, 9.50000000e+00, 3.52688400e+04,
       3.96258000e+03, 1.78410000e+03, 4.45210000e+02, 2.00450000e+02,
       9.02500000e+01, 6.62348815e+06, 7.44172524e+05, 3.35053980e+05,
       8.36104380e+04, 3.76445100e+04, 1.69489500e+04, 9.39393100e+03,
       4.22949500e+03, 1.90427500e+03, 8.57375000e+02])

In [18]:
scaled_X_train[0]

array([ 0.455913  , -0.15469995, -0.98899258,  0.23144458,  0.12990319,
       -0.57856073, -0.43655678, -0.66806654, -0.71668198,  0.02389419,
        0.04869878, -0.45436665, -0.22089285, -0.47664217, -0.51504813,
       -0.55818067, -0.60618091, -0.56426029, -0.5063835 ])

In [19]:
from sklearn.linear_model import Ridge

In [20]:
ridge_model = Ridge(alpha=10)

In [21]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [22]:
test_prediction = ridge_model.predict(X_test)
test_prediction

array([14.09843862, 20.28498697, 13.19563787, 16.3598524 ,  7.47463038,
        7.08310045, 20.80073699, 18.82089672, 13.70687674, 20.10199097,
        9.09616278, 16.81173761, 17.11406413, 22.49043245, 18.72312086,
        9.1407274 , 17.9201821 , 11.18995081,  9.01586235, 21.38988241,
        6.99048938, 18.98888775, 26.877109  , 23.79341609, 10.30653924,
       15.21166467, 20.88312842,  9.9106231 , 15.49049314,  8.43666945,
        8.88229934, 20.03626878, 13.75893766,  7.75501144, 18.1327548 ,
       10.46800898, 11.37818984, 11.4972816 ,  7.44159579, 14.65522584,
       13.20021585, 12.81627595, 12.09446959,  8.18916775, 11.53872386,
       10.7400564 ,  5.37383835, 17.84261996, 15.44810151, 22.04219807,
       10.16936782, 16.63365914, 19.04468049, 13.65589932, 15.74508701,
        5.27499306, 24.04839616,  9.07835483, 19.86787384, 16.79910558,
       16.9353248 , 24.78169927,  9.92206181, 20.59312234, 15.85234188,
       21.64679324])

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

1.13997288873853

In [24]:
MSE = mean_squared_error(y_test, test_prediction)
MSE

2.2160383097108833

In [25]:
MAE = mean_absolute_error(y_test, test_prediction)
MAE

1.13997288873853

In [26]:
RMSE = np.sqrt(mean_squared_error(y_test, test_prediction))
RMSE

1.48863639271344